packages:
  - apps/*
allowBuilds:
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
