spring.application.name=FoodEx-Web
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.url=jdbc:h2:file:./temp/db
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=ALWAYS


spring.security.oauth2.client.registration.authsch.provider=authsch
spring.security.oauth2.client.registration.authsch.client-id=TODO
spring.security.oauth2.client.registration.authsch.client-secret=TODO
spring.security.oauth2.client.registration.authsch.scope=openid,profile,email,meta.bme.hu:unitScope,pek.sch.bme.hu:profile
spring.security.oauth2.client.registration.authsch.redirect-uri=http://localhost:8080/login/oauth2/code/authsch
spring.security.oauth2.client.provider.authsch.issuer-uri=https://auth.sch.bme.hu
spring.security.oauth2.client.provider.authsch.user-name-attribute=name
